### ISSUE TITLE
Should submissions in private messages be allowed?

### ISSUE THREAD

**Issue by jeremybanks** [cliss/accidentalbot#31]
The bot processes any messages it receives, even if they're in private messages. I used this to submit an XSS that caused everyone to vote for my title early in the episode, any nobody realized because my suspicious-looking message wasn't in that chat room for them to see.

Is there any value in accepting titles and links in private messages, or should it only consider messages from the chat room?

**Comment by cliss** [comment]
Fixed in 42d8bae0724b4949faa1e72da00c6450d71f8697
