### ISSUE TITLE
Titles and Links Co-Mingle

### ISSUE THREAD

**Issue by robmathers** [cliss/accidentalbot#35]
During tonight's recording, I noticed that a submitted link got mixed in with the show titles. A reload appeared to fix it, but then I saw a title mixed in with the links section. Screenshots:

![screen shot 2014-07-21 at 10 03 02 pm](https://cloud.githubusercontent.com/assets/4419005/3652876/908a61ce-1145-11e4-86b4-ce8f9d4b7cbf.png)
![screen shot 2014-07-21 at 10 09 41 pm](https://cloud.githubusercontent.com/assets/4419005/3652877/92c4c308-1145-11e4-9062-a3e60e17de51.png)

I don't have any useful steps to reproduce, but I'm submitting it for posterity. The rendered DOM output (from Safari Web Inspector) can be found in [this gist](https://gist.github.com/robmathers/676c26bf605d5b2fbb71), search for `data-id="0"` to find the errand link.

**Comment by cliss** [comment]
Hasn't been an issue in a long time. Assuming fixed.
