### ISSUE TITLE
Fix malicious votes by making websocket one-way only

### ISSUE THREAD

**Issue by voldyman** [cliss/accidentalbot#9]
The easy was to fix vote flooding is to use websockets just for broadcasting and use http post requests up votes.

malicious votes can be stopped by using either a Captch or generating unique id's for each GET / requests and using those id's to verify the vote. The uid's can be removed from the list of id's after some time too.

whenever a valid vote is received, use websockets to update all the connected clients.

**Comment by cliss** [comment]
Completely fair, but not something that I intend to fix. Thankfully, not much malicious activity has happened in a long time.

Should you wish to issue a pull request, I'm happy to take a look.
